# Generated by Django 3.1 on 2020-08-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listed_by',
        ),
    ]
