# Generated by Django 3.1 on 2020-08-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_listed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
