# Generated by Django 3.1 on 2020-08-21 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_delete_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bidding_closed', models.BooleanField()),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
