# Generated by Django 3.1 on 2020-08-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidding_closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('toy', 'Toy'), ('book', 'Book'), ('jewelry', 'Jewelry'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('home', 'Home')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
