# Generated by Django 3.1 on 2020-08-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200823_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Toy', 'Toy'), ('Book', 'Book'), ('Jewelry', 'Jewelry'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Home', 'Home')], max_length=15, null=True),
        ),
    ]
