# Generated by Django 3.1 on 2020-08-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200825_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='picture',
        ),
    ]
