# Generated by Django 3.1 on 2020-08-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
