# Generated by Django 3.1 on 2020-08-30 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200830_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
